version: '3.6'
services:
  saigar-ui:
    image: saigar-ctf:latest
    ports:
    - "5000:5000"
    depends_on:
    - "graphql-engine"
    restart: always
    build: .
  saigar-auth:
    image: saigar-auth:latest
    ports:
    - "3000:3000"
    restart: always
    build: services/auth
  saigar-file-upload:
    image: saigar-fu:latest
    ports:
    - "7000:7000"
    restart: always
    build: services/file-upload