version: '3.6'
services:
  saigar-ui:
    image: saigar-ctf:1.09-26.1
    ports:
    - "127.0.0.1:5000:5000"
    restart: always
    build: .
  saigar-auth:
    image: saigar-auth:1.09-26.1
    ports:
    - "127.0.0.1:3000:3000"
    restart: always
    build: services/auth